version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "blog-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-5d9xb17vn9vo"
s3_prefix = "blog-api"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
